# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://hnguyen999.github.io/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hang Nguyen
  url:               https://www.linkedin.com/in/hang-nguyen-93a53070/
  email:             hnguyen0@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
